//layout.js
// import Button from '@mui/material/Button';
// import './Styles.module.scss'
// import "./globals.css";

import "bootstrap/dist/css/bootstrap.min.css"
import AddBootstrap from "./AddBootstrap";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

import "./styles.css";

export const metadata = {
  title: "NextJs and Bootstrap 5",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        <AddBootstrap />
          {children}
        <Footer />
      </body>
    </html>
  );
}